### ISSUE TITLE
Add Complete GPIO Example 

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/Venjix#6]
to make sure everyone can use this app, It need proper tutorial and documentation. such as, but not limited to:

- [x] Add Arduino Example
- [ ] Add Raspberry PI Example
- [x] Add Web-hook Example
- [x] Add Telegram Bot Example

**Comment by fahminlb33** [comment]
Yes, I'm currently planning to make an example using ESP8266. In the mean time, this project still missing some of it's core features like the Dashboard. I'll create a new issue on ESP8266 tutorial.

**Comment by fahminlb33** [comment]
Most of the checklist is already solved. For the Raspberry Pi example, I cannot provide those info since I don't have the hardware in hand.

**Comment by rasyidf** [comment]
It would be great if you allow wiki to be edited ✌🏼

**Comment by fahminlb33** [comment]
It seems like the Raspberry Pi example will not be completed in this release because of none of the current contributor has access to one. Future RPI example should be mentioned in a new issue.
