### ISSUE TITLE
Disallow superadmin to change role.

### ISSUE THREAD

**Issue by rasyidf** [fahminlb33/Venjix#8]
The admin account currently able to change into normal users, it's problematic when the user with only one administrator, accidentally apply those rules. so there's no anyone left to be an admin.  

![image](https://user-images.githubusercontent.com/28984914/103466547-b6030e80-4d78-11eb-80da-8a63a75fcb2b.png)

Suggested Workaround for this:

- Disable role change for single admin account.  
- Set another user to be admin. let the current admin to choose another admin. before changing their own role.

**Comment by fahminlb33** [comment]
Thanks for the insight! I'll fix this in near future, maybe next week if I have the time. Do you want to create a PR for this issue? I'll assign you to this issue.
